services:
  postgres_db:
    image: postgres:16-alpine
    container_name: investnow_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - investnow-net
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CATALOG_SERVICE_URL=http://catalog_service:8000
      - WALLET_SERVICE_URL=http://wallet_service:8000
      - ORDER_SERVICE_URL=http://order_service:8000
    depends_on:
      - catalog_service
      - wallet_service
      - order_service
    networks:
      - investnow-net
    volumes:
      - ./app/config:/app/app/config

  wallet_service:
    build:
      context: .
      dockerfile: docker/wallet/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - investnow-net
    volumes:
      - ./app/config:/app/config

  catalog_service:
    build:
      context: .
      dockerfile: docker/catalog/Dockerfile
    ports:
      - "8002:8000"
    networks:
      - investnow-net
    volumes:
      - ./app/config:/app/config

  order_service:
    build:
      context: .
      dockerfile: docker/order/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - CATALOG_SERVICE_URL=${CATALOG_SERVICE_URL}
      - WALLET_SERVICE_URL=${WALLET_SERVICE_URL}
    depends_on:
      - catalog_service
      - wallet_service
    networks:
      - investnow-net
    volumes:
      - ./app/config:/app/config

volumes:
  pgdata:

networks:
  investnow-net:
    name: investnow-net
    driver: bridge