version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: investnow_db
    environment:
      POSTGRES_USER: investnow_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: investnow_wallet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - investnow-net

  wallet_service:
    build:
      context: .
      dockerfile: docker/wallet/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://investnow_user:secure_password@postgres_db:5432/investnow_wallet_db
    depends_on:
      - postgres_db
    networks:
      - investnow-net
    volumes:
      - ./app/config:/app/config

  catalog_service:
    build:
      context: .
      dockerfile: docker/catalog/Dockerfile
    ports:
      - "8002:8000"
    networks:
      - investnow-net
    volumes:
      - ./app/config:/app/config

  order_service:
    build:
      context: .
      dockerfile: docker/order/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - CATALOG_SERVICE_URL=http://catalog_service:8000
      - WALLET_SERVICE_URL=http://wallet_service:8000
    depends_on:
      - catalog_service
      - wallet_service
    networks:
      - investnow-net
    volumes:
      - ./app/config:/app/config

volumes:
  pgdata:

networks:
  investnow-net:
    driver: bridge